#!/usr/bin/env python3
"""Generate the transition preset table from VEGAS's own PresetPackage.xml.

VEGAS ships every stock transition preset as plain XML inside the Vfx1 OFX bundle:

    OFX Video Plug-Ins/Vfx1.ofx.bundle/Contents/Presets/PresetPackage.xml

215 transition presets across 24 plug-ins, each with typed parameter values. That makes
it the source of truth — no decompilation involved, and far better than transcribing
names off screenshots or recovering only the handful a sample project happens to use.

Run from the repo root:

    python tools/gen_transition_presets.py > src/video/TransitionPresetData.cpp

The output is committed so a build needs no VEGAS install; re-run it when the reference
copy under SAMPLES/ is updated.
"""

import sys
import xml.etree.ElementTree as ET
from collections import OrderedDict

XML = ("SAMPLES/VEGAS-PRO-22-PROGRAM-FILES/OFX Video Plug-Ins/Vfx1.ofx.bundle/"
       "Contents/Presets/PresetPackage.xml")

# VEGAS parameter name -> the key OpenVegas already uses for it. Groups that shipped
# before this generator keep their existing keys so saved projects still resolve; the
# rest fall back to the plain rule below (first letter lowercased).
ALIASES = {
    "NumberOfBlinds": "count",
    "SpecularLight": "specularLight",
    "ExtraSpins": "extraSpins",
    "FeatherAngle": "featherAngle",
    "BorderSize": "borderSize",
    "BorderFeather": "borderFeather",
    # RGB expands per component, so this yields borderRed / borderGreen / borderBlue —
    # the keys the renderers and the properties window already use.
    "BorderColor": "border",
    "Border": "borderSize",
}

# A few plug-ins name the same idea differently. Iris calls the border colour "Color"
# and its width "Border", so it needs its own mapping rather than a global rule that
# would misname the field in every other group.
PLUGIN_ALIASES = {
    "iris": {"Color": "border"},
}

# Vector parameters expand into one scalar per component, since the properties window
# has no vector control and the renderers read plain doubles.
COMPONENTS = {
    "Double2D": ("X", "Y"),
    "RGB": ("Red", "Green", "Blue"),
    "RGBA": ("Red", "Green", "Blue", "Alpha"),
    "Double3D": ("X", "Y", "Z"),
}


def key_for(name, plugin=None):
    per = PLUGIN_ALIASES.get(plugin, {})
    if name in per:
        return per[name]
    if name in ALIASES:
        return ALIASES[name]
    return name[0].lower() + name[1:]


def component_key(name, suffix, plugin=None):
    return key_for(name, plugin) + suffix


def main():
    root = ET.parse(XML).getroot()
    groups = OrderedDict()

    for preset in root.findall("OfxPreset"):
        if preset.get("context") != "Transition":
            continue
        plugin = preset.get("plugin").split(":")[-1]
        entries = []
        for child in preset:
            if not child.tag.startswith("OfxParamType"):
                continue
            kind = child.tag[len("OfxParamType"):]
            name = child.get("name")
            values = [v.text.strip() for v in child.findall("OfxParamValue")]
            if not values:
                continue
            # "Transition" is the plug-in's own progress input, driven by the timeline
            # rather than stored as a setting.
            if name == "Transition":
                continue
            if kind in COMPONENTS:
                parts = values[0].split()
                for suffix, raw in zip(COMPONENTS[kind], parts):
                    entries.append((component_key(name, suffix, plugin), float(raw)))
            elif kind == "Boolean":
                entries.append((key_for(name, plugin), 1.0 if values[0] in ("1", "true") else 0.0))
            elif kind in ("Double", "Integer", "Choice"):
                entries.append((key_for(name, plugin), float(values[0])))
            # Custom / Image parameters carry data no slider can express; skipped.
        groups.setdefault(plugin, []).append((preset.get("name"), entries))

    out = sys.stdout
    out.write("// Generated by tools/gen_transition_presets.py - do not edit by hand.\n")
    out.write("//\n")
    out.write("// Source: VEGAS's own PresetPackage.xml inside the Vfx1 OFX bundle, which\n")
    out.write("// ships every stock transition preset with its parameter values.\n\n")
    out.write('#include "video/TransitionPresetData.h"\n\n')
    out.write("namespace openvegas {\n\n")
    out.write("const QVector<StockTransitionGroup> &stockTransitionPresets()\n{\n")
    out.write("    static const QVector<StockTransitionGroup> groups = {\n")

    for plugin, presets in groups.items():
        out.write('        {QStringLiteral("%s"),\n         {\n' % plugin)
        for name, entries in presets:
            escaped = name.replace('"', '\\"')
            pairs = ", ".join(
                '{QStringLiteral("%s"), %s}' % (k, repr(round(v, 6)))
                for k, v in entries)
            out.write('             {QStringLiteral("%s"), {%s}},\n' % (escaped, pairs))
        out.write("         }},\n")

    out.write("    };\n    return groups;\n}\n\n")
    out.write("} // namespace openvegas\n")

    total = sum(len(v) for v in groups.values())
    sys.stderr.write("groups: %d, presets: %d\n" % (len(groups), total))


if __name__ == "__main__":
    main()
